loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))() 
task.wait(0.12) 
loadstring(game:HttpGet("https://raw.githubusercontent.com/Moneee556/SubConfig/main/SubConfig", true))()
task.wait(0.12)
loadstring(game:HttpGet("https://raw.githubusercontent.com/LolcoolLol/scripts/main/cool.lua", true))() 
loadstring(game:HttpGet("https://raw.githubusercontent.com/LolcoolLol/scripts/main/cool.lua", true))()
