local ScreenGui = Instance.new("ScreenGui")
local Frame = Instance.new("Frame")
local UICorner = Instance.new("UICorner")
local shadowHolder = Instance.new("Frame")
local umbraShadow = Instance.new("ImageLabel")
local penumbraShadow = Instance.new("ImageLabel")
local ambientShadow = Instance.new("ImageLabel")
local Frame_2 = Instance.new("Frame")
local TextLabel = Instance.new("TextLabel")
local UIGradient = Instance.new("UIGradient")
local flash_on = Instance.new("ImageButton")
local TextBox = Instance.new("TextBox")
local UICorner_2 = Instance.new("UICorner")
local TextLabel_2 = Instance.new("TextLabel")
local UICorner_3 = Instance.new("UICorner")
local group = Instance.new("ImageButton")
local TextLabel_3 = Instance.new("TextLabel")
local UICorner_4 = Instance.new("UICorner")
local web_asset = Instance.new("ImageButton")
local TextLabel_4 = Instance.new("TextLabel")
local UICorner_5 = Instance.new("UICorner")
local favorite_border = Instance.new("ImageButton")
local TextLabel_5 = Instance.new("TextLabel")
local UICorner_6 = Instance.new("UICorner")
local TextLabel_6 = Instance.new("TextLabel")
local UICorner_7 = Instance.new("UICorner")
local visibility = Instance.new("ImageButton")
local TextLabel_7 = Instance.new("TextLabel")
local UICorner_8 = Instance.new("UICorner")
local insert_comment = Instance.new("ImageButton")
local search = Instance.new("ImageButton")
local power = Instance.new("ImageButton")
local account_circle = Instance.new("ImageButton")
local TextLabel_8 = Instance.new("TextLabel")
local UIGradient_2 = Instance.new("UIGradient")
local Frame_3 = Instance.new("Frame")
local TextLabel_9 = Instance.new("TextLabel")
local UIGradient_3 = Instance.new("UIGradient")
local TextLabel_10 = Instance.new("TextLabel")
local shadowHolder_2 = Instance.new("Frame")
local umbraShadow_2 = Instance.new("ImageLabel")
local penumbraShadow_2 = Instance.new("ImageLabel")
local ambientShadow_2 = Instance.new("ImageLabel")
local Frame_4 = Instance.new("Frame")
local TextLabel_11 = Instance.new("TextLabel")
local UIGradient_4 = Instance.new("UIGradient")
local TextLabel_12 = Instance.new("TextLabel")
local shadowHolder_3 = Instance.new("Frame")
local umbraShadow_3 = Instance.new("ImageLabel")
local penumbraShadow_3 = Instance.new("ImageLabel")
local ambientShadow_3 = Instance.new("ImageLabel")
local Frame_5 = Instance.new("Frame")
local TextLabel_13 = Instance.new("TextLabel")
local UIGradient_5 = Instance.new("UIGradient")
local TextLabel_14 = Instance.new("TextLabel")
local shadowHolder_4 = Instance.new("Frame")
local umbraShadow_4 = Instance.new("ImageLabel")
local penumbraShadow_4 = Instance.new("ImageLabel")
local ambientShadow_4 = Instance.new("ImageLabel")
local Frame_6 = Instance.new("Frame")
local TextLabel_15 = Instance.new("TextLabel")
local UIGradient_6 = Instance.new("UIGradient")
local TextLabel_16 = Instance.new("TextLabel")
local shadowHolder_5 = Instance.new("Frame")
local umbraShadow_5 = Instance.new("ImageLabel")
local penumbraShadow_5 = Instance.new("ImageLabel")
local ambientShadow_5 = Instance.new("ImageLabel")
local Frame_7 = Instance.new("Frame")
local TextLabel_17 = Instance.new("TextLabel")
local UIGradient_7 = Instance.new("UIGradient")
local TextLabel_18 = Instance.new("TextLabel")
local shadowHolder_6 = Instance.new("Frame")
local umbraShadow_6 = Instance.new("ImageLabel")
local penumbraShadow_6 = Instance.new("ImageLabel")
local ambientShadow_6 = Instance.new("ImageLabel")
local Frame_8 = Instance.new("Frame")
local TextLabel_19 = Instance.new("TextLabel")
local UIGradient_8 = Instance.new("UIGradient")
local TextLabel_20 = Instance.new("TextLabel")
local shadowHolder_7 = Instance.new("Frame")
local umbraShadow_7 = Instance.new("ImageLabel")
local penumbraShadow_7 = Instance.new("ImageLabel")
local ambientShadow_7 = Instance.new("ImageLabel")
local FPS = Instance.new("Frame")
local UICorner_9 = Instance.new("UICorner")
local TextLabel_21 = Instance.new("TextLabel")
local UIGradient_9 = Instance.new("UIGradient")
local TextLabel_22 = Instance.new("TextLabel")
local shadowHolder_8 = Instance.new("Frame")
local umbraShadow_8 = Instance.new("ImageLabel")
local penumbraShadow_8 = Instance.new("ImageLabel")
local ambientShadow_8 = Instance.new("ImageLabel")
local TextLabel_23 = Instance.new("TextLabel")
local ScrollingFrame = Instance.new("ScrollingFrame")
local UIGridLayout = Instance.new("UIGridLayout")
local Killaura = Instance.new("TextButton")
local UICorner_10 = Instance.new("UICorner")
local UIGradient_10 = Instance.new("UIGradient")
local TextLabel_24 = Instance.new("TextLabel")
local TextLabel_25 = Instance.new("TextLabel")
local settings = Instance.new("ImageButton")
local cloud = Instance.new("ImageButton")
local Fly = Instance.new("TextButton")
local UICorner_11 = Instance.new("UICorner")
local UIGradient_11 = Instance.new("UIGradient")
local TextLabel_26 = Instance.new("TextLabel")
local TextLabel_27 = Instance.new("TextLabel")
local settings_2 = Instance.new("ImageButton")
local cloud_2 = Instance.new("ImageButton")
local InstantKill = Instance.new("TextButton")
local UICorner_12 = Instance.new("UICorner")
local UIGradient_12 = Instance.new("UIGradient")
local TextLabel_28 = Instance.new("TextLabel")
local TextLabel_29 = Instance.new("TextLabel")
local settings_3 = Instance.new("ImageButton")
local cloud_3 = Instance.new("ImageButton")
local security = Instance.new("ImageButton")

--Properties:

ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling


TextLabel_8.Parent = ScreenGui
TextLabel_8.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_8.BackgroundTransparency = 1.000
TextLabel_8.BorderColor3 = Color3.fromRGB(0, 0, 0)
TextLabel_8.BorderSizePixel = 0
TextLabel_8.Position = UDim2.new(-0.0000000000000, 25, 0, 0)
TextLabel_8.Size = UDim2.new(0, 200, 0, 50)
TextLabel_8.Font = Enum.Font.GothamBold
TextLabel_8.Text = "Lyno 8.0"
TextLabel_8.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_8.TextSize = 60.000

UIGradient_2.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(55, 206, 223)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(91, 136, 229))}
UIGradient_2.Parent = TextLabel_8

Frame_3.Parent = ScreenGui
Frame_3.BackgroundColor3 = Color3.fromRGB(67, 67, 67)
Frame_3.BackgroundTransparency = 0.600
Frame_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Frame_3.BorderSizePixel = 0
Frame_3.Position = UDim2.new(0.897093892, 0, 0.0132211745, 0)
Frame_3.Size = UDim2.new(0, 202, 0, 27)

TextLabel_9.Parent = Frame_3
TextLabel_9.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_9.BackgroundTransparency = 1.000
TextLabel_9.BorderColor3 = Color3.fromRGB(0, 0, 0)
TextLabel_9.BorderSizePixel = 0
TextLabel_9.Position = UDim2.new(-0.184100419, 0, -0.444444448, 0)
TextLabel_9.Size = UDim2.new(0, 200, 0, 50)
TextLabel_9.Font = Enum.Font.GothamBold
TextLabel_9.Text = "Cheat Detector"
TextLabel_9.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_9.TextSize = 14.000

UIGradient_3.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(55, 206, 223)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(91, 136, 229))}
UIGradient_3.Parent = TextLabel_9

TextLabel_10.Parent = Frame_3
TextLabel_10.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_10.BackgroundTransparency = 1.000
TextLabel_10.BorderColor3 = Color3.fromRGB(0, 0, 0)
TextLabel_10.BorderSizePixel = 0
TextLabel_10.Position = UDim2.new(0.284995228, 0, -0.444444448, 0)
TextLabel_10.Size = UDim2.new(0, 200, 0, 50)
TextLabel_10.Font = Enum.Font.GothamBold
TextLabel_10.Text = "Client Side"
TextLabel_10.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_10.TextSize = 14.000

shadowHolder_2.Name = "shadowHolder"
shadowHolder_2.Parent = Frame_3
shadowHolder_2.BackgroundTransparency = 1.000
shadowHolder_2.Size = UDim2.new(1, 0, 1, 0)
shadowHolder_2.ZIndex = 0

umbraShadow_2.Name = "umbraShadow"
umbraShadow_2.Parent = shadowHolder_2
umbraShadow_2.AnchorPoint = Vector2.new(0.5, 0.5)
umbraShadow_2.BackgroundTransparency = 1.000
umbraShadow_2.Position = UDim2.new(0.5, 0, 0.5, 8)
umbraShadow_2.Size = UDim2.new(1, 10, 1, 10)
umbraShadow_2.ZIndex = 0
umbraShadow_2.Image = "rbxassetid://1316045217"
umbraShadow_2.ImageColor3 = Color3.fromRGB(0, 0, 0)
umbraShadow_2.ImageTransparency = 0.860
umbraShadow_2.ScaleType = Enum.ScaleType.Slice
umbraShadow_2.SliceCenter = Rect.new(10, 10, 118, 118)





TextLabel_11.Parent = Frame_4
TextLabel_11.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_11.BackgroundTransparency = 1.000
TextLabel_11.BorderColor3 = Color3.fromRGB(0, 0, 0)
TextLabel_11.BorderSizePixel = 0
TextLabel_11.Position = UDim2.new(-0.184100419, 0, -0.444444448, 0)
TextLabel_11.Size = UDim2.new(0, 200, 0, 50)
TextLabel_11.Font = Enum.Font.GothamBold
TextLabel_11.Text = "Cheat Detector"
TextLabel_11.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_11.TextSize = 14.000

UIGradient_4.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(55, 206, 223)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(91, 136, 229))}
UIGradient_4.Parent = TextLabel_11

TextLabel_12.Parent = Frame_4
TextLabel_12.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_12.BackgroundTransparency = 1.000
TextLabel_12.BorderColor3 = Color3.fromRGB(0, 0, 0)
TextLabel_12.BorderSizePixel = 0
TextLabel_12.Position = UDim2.new(0.284995228, 0, -0.444444448, 0)
TextLabel_12.Size = UDim2.new(0, 200, 0, 50)
TextLabel_12.Font = Enum.Font.GothamBold
TextLabel_12.Text = "Client Side"
TextLabel_12.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel_12.TextSize = 14.000

shadowHolder_3.Name = "shadowHolder"
shadowHolder_3.Parent = Frame_4
shadowHolder_3.BackgroundTransparency = 1.000
shadowHolder_3.Size = UDim2.new(1, 0, 1, 0)
shadowHolder_3.ZIndex = 0

umbraShadow_3.Name = "umbraShadow"
umbraShadow_3.Parent = shadowHolder_3
umbraShadow_3.AnchorPoint = Vector2.new(0.5, 0.5)
umbraShadow_3.BackgroundTransparency = 1.000
umbraShadow_3.Position = UDim2.new(0.5, 0, 0.5, 8)
umbraShadow_3.Size = UDim2.new(1, 10, 1, 10)
umbraShadow_3.ZIndex = 0
umbraShadow_3.Image = "rbxassetid://1316045217"
umbraShadow_3.ImageColor3 = Color3.fromRGB(0, 0, 0)
umbraShadow_3.ImageTransparency = 0.860
umbraShadow_3.ScaleType = Enum.ScaleType.Slice
umbraShadow_3.SliceCenter = Rect.new(10, 10, 118, 118)

penumbraShadow_3.Name = "penumbraShadow"
penumbraShadow_3.Parent = shadowHolder_3
penumbraShadow_3.AnchorPoint = Vector2.new(0.5, 0.5)
penumbraShadow_3.BackgroundTransparency = 1.000
penumbraShadow_3.Position = UDim2.new(0.5, 0, 0.5, 8)
penumbraShadow_3.Size = UDim2.new(1, 10, 1, 10)
penumbraShadow_3.ZIndex = 0
penumbraShadow_3.Image = "rbxassetid://1316045217"
penumbraShadow_3.ImageColor3 = Color3.fromRGB(0, 0, 0)
penumbraShadow_3.ImageTransparency = 0.880
penumbraShadow_3.ScaleType = Enum.ScaleType.Slice
penumbraShadow_3.SliceCenter = Rect.new(10, 10, 118, 118)